// <auto-generated />
using System;
using BitirmeCalismasiAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BitirmeCalismasiAPI.Migrations
{
    [DbContext(typeof(BitirmeContext))]
    [Migration("20210425114832_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BitirmeCalismasiAPI.Models.Bileklik", b =>
                {
                    b.Property<int>("BileklikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("TakilmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("BileklikID");

                    b.ToTable("Bilekliks");
                });

            modelBuilder.Entity("BitirmeCalismasiAPI.Models.Hasta", b =>
                {
                    b.Property<int>("HastaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BileklikID")
                        .HasColumnType("int");

                    b.Property<string>("HastaAcikAdres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaIletisimNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("HastaKonumX")
                        .HasColumnType("float");

                    b.Property<double>("HastaKonumY")
                        .HasColumnType("float");

                    b.Property<string>("HastaOyku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HastaSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HastaYas")
                        .HasColumnType("int");

                    b.Property<int>("PersonelID")
                        .HasColumnType("int");

                    b.HasKey("HastaID");

                    b.ToTable("Hastas");
                });

            modelBuilder.Entity("BitirmeCalismasiAPI.Models.Personel", b =>
                {
                    b.Property<int>("PersonelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PersonelAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSifre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonelSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonelID");

                    b.ToTable("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
